apiVersion: v1
kind: Service
metadata:
  name: stackrox-mcp
  labels:
    {{- include "stackrox-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "stackrox-mcp.selectorLabels" . | nindent 4 }}
